language: node_js
node_js:
  - "node"
addons:
  ssh_known_hosts: 77.72.0.122:722
before_install:
  - cd website
install: npm install
script:
  - echo "no tests"
before_deploy:
  - npm run build
  - cd ../
  - openssl aes-256-cbc -K $encrypted_43adbc9a54a6_key -iv $encrypted_43adbc9a54a6_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: scp -r -P 722 $TRAVIS_BUILD_DIR/website/build/unininja/* unininja@uni.ninja:~/public_html
